dev:
  catalog_name: mlops_dev
  schema_name: diegocan

acc:
  catalog_name: mlops_acc
  schema_name: diegocan

prd:
  catalog_name: mlops_prd
  schema_name: diegocan

num_features:
  - t00
  - t01
  - t02
  - t03
  - t04
  - t05
  - t06
  - t07
  - t08
  - t09
  - t10
  - t11
  - t12
  - t13
  - t14
  - t15
  - t16
  - t17
  - t18
  - t19
  - t20
  - t21
  - t22
  - t23

target:
  - frost_next_day

parameters:
  - learning_rate: 0.1
  - n_estimators: 100
  - max_depth: 3
  - num_leaves: 31
  - min_child_samples: 20
  - subsample: 0.8
  - colsample_bytree: 0.8
